# Generated by Django 5.2.7 on 2025-10-22 00:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StringEntry',
            fields=[
                ('sha256_hash', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('value', models.TextField(unique=True)),
                ('length', models.IntegerField()),
                ('is_palindrome', models.BooleanField()),
                ('unique_characters', models.IntegerField()),
                ('word_count', models.IntegerField()),
                ('character_frequency_map', models.JSONField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
